(function () {
    var carsImages = ["Chevrolet-icon", "Spark", "Sonic hatch"]; //images from folder models
    var selectModel = document.getElementById("select-model");
    var carImg = document.getElementById("acces-car-img");
    var modelName = document.getElementById("model-name");
    selectModel.addEventListener("change", function () {
        var i = selectModel.selectedIndex;
        modelName.innerHTML = selectModel.options[i].text;
        carImg.src = "images/models/" + carsImages[i] + ".png"; });
})();

var app = angular.module("carApp", []);
app.controller("carCtrl", function ($scope) {
    $scope.spark = [
        { "image": "images/chevy spark/Accessories/acc_1.jpg", "header": "Передній центральний органайзер з відсіками", "description": "Тримайте всі Ваші необхідні для подорожі маленькі предмети в передньому центральному органайзері.", "art_num": "Арт. № 42402540", "price": "20" },
        { "image": "images/chevy spark/Accessories/acc_2.jpg", "header": "Центральний ковпачок з логотипом Chevrolet", "description": "Прикрасьте зовнішній вигляд коліс Вашого Spark цими відмінними центральними ковпачками.", "art_num": "Арт. № 42371986", "price": "20" },
        { "image": "images/chevy spark/Accessories/acc_3.jpg", "header": "Бокові молдинги вікон", "description": "Боковиі молдинги вікон додають новий вимір в стилі для спортивного вигляду Chevrolet Spark.", "art_num": "Арт. № 42345006", "price": "25" },
        { "image": "images/chevy spark/Accessories/acc_4.jpg", "header": "Болти з секретом для колісних дисків", "description": 'Захистіть колісні диски "секретними" болтами. Їх можна зняти лише за допомогоюспеціального ключа, що міститься в комплекті.', "art_num": "Арт. № 12498078", "price": "40" },
        { "image": "images/chevy spark/Accessories/acc_5.jpg", "header": "Вставки в легкосплавні диски", "description": "Додайте колесам Вашого Spark екслюзивного вигляду відмінними вставками червоного або сірого кольору. Продаються в наборах по 5 на 15-дюймові колеса.", "art_num": "Арт. № 42352081", "price": "50" },
        { "image": "images/chevy spark/Accessories/acc_6.jpg", "header": "Комплект для куріння", "description": "Попільничка ідеально підходить до стандартного тримача чашок і легко виймається. Попільничка легко чиститься, має глибоке дно та інтегровану кришку, запобігає розсіюванню попелу – нею зручно користуватись як водію, так і пасажиру. Комплект включає в себе попільничку з пластику, прикурювача та тримача прикурювача.", "art_num": "Арт. № 42421072", "price": "55" },
        { "image": "images/chevy spark/Accessories/acc_7.jpg", "header": "Накладки на корпус зовнішніх дзеркал", "description": "Додай завершальний штрих до свого Spark яскравими накладками.", "art_num": "Арт. № 94517500", "price": "65" },
        { "image": "images/chevy spark/Accessories/acc_8.jpg", "header": "Алюмінієві накладки на пороги дверей", "description": "Допомагає захистити пороги дверей Вашого Spark від подряпин та потертостей цими алюмінієвими накладками.", "art_num": "Арт. № 95075440", "price": "75" },
        { "image": "images/chevy spark/Accessories/acc_9.jpg", "header": "Накладка на дверну ручку", "description": "Замініть заводські дверні ручки Вашого Spark на передні і задні хромовані ручки для стильного, вишуканого і особистого зовнішнього вигляду.", "art_num": "Арт. № 42417263", "price": "80" },
        { "image": "images/chevy spark/Accessories/acc_10.jpg", "header": "Набір килимків Premium", "description": "Передні і задні килимки Premium допомагають захистити підлогу Вашого Spark від бруду та сміття. Спеціальні титанові фіксатори утримують їх на місці для забезпечення додаткової безпеки.", "art_num": "Арт. № 42392357", "price": "100" },
        { "image": "images/chevy spark/Accessories/acc_11.jpg", "header": "Спортивні накладки на педалі", "description": "Накладки на педалі з нержавієючої сталі створюють неповторний спортивний імідж для Вашого Chevrolet Spark з механічною або автоматичною трансмісією.", "art_num": "Арт. № 94523283", "price": "110" },
        { "image": "images/chevy spark/Accessories/acc_12.jpg", "header": "Декоративна накладка панелі приладів", "description": "Додай кольоровою накладкою центральній консолі ще більш елегантного вигляду. В наявності є різні кольори.", "art_num": "Арт. № 42371915", "price": "125" },
        { "image": "images/chevy spark/Accessories/acc_13.jpg", "header": "Органайзер для багажу", "description": "Цей міцний, гнучкий, складаний органайзер дозволяє первозити легкі предмети різних розмірів. Органайзер для багажу має кілька відсіків і може бути складений плоско і вийнятий з транспортного засобу в разі потреби. Має чорний колір та логотип Chevrolet.", "art_num": "Арт. № 95483420", "price": "150" },
        { "image": "images/chevy spark/Accessories/acc_14.jpg", "header": "Накладка на решітку радіатора", "description": "Декоративна решітка радіатора придасть вашому автомобілю ексклюзивного вигляду. Ідеально підходить та легко установлювається.", "art_num": "Арт. № 42400342", "price": "150" },
        { "image": "images/chevy spark/Accessories/acc_15.jpg", "header": "Боковий захисний молдинг", "description": "Додайте Вашому Spark стильний та ефективний захист панелей дверей від дрібних подряпин. Доступні у чорному кольорі або може бути підібрані під колір Вашого авто.", "art_num": "Арт. № 95333634", "price": "190" },
        { "image": "images/chevy spark/Accessories/acc_16.jpg", "header": "Декоративна плівка", "description": "Додай виразний та яскравий штрих до Вашого Spark. Для автомобілів без люку на даху.", "art_num": "Арт. № 95244906", "price": "200" },
        { "image": "images/chevy spark/Accessories/acc_17.jpg", "header": "Декоративна накладка на задній бампер", "description": "Оберіть високоякісну накладку заднього бампера – і назавжди забудьте про дрібні пошкодження кузова Вашого автомобіля.", "art_num": "Арт. № 95264903", "price": "200" },
        { "image": "images/chevy spark/Accessories/acc_18.jpg", "header": "Комплект протитуманних фар", "description": "Підкреслюють стильний дизайн Chevrolet Spark і підвищують безпеку, покращуючи видимість під час несприятливих погодних умов.", "art_num": "Арт. № 42348907", "price": "225" },
        { "image": "images/chevy spark/Accessories/acc_19.jpg", "header": "Розширювач переднього бампера та зовнішніх порогів", "description": "Надайте Вашому автомобілю спортивний вигляд та додаткову аеродинаміку. Всі елементи відповідають найвищим стандартам якості та надійності, а також ідеально підходять до Вашого автомобіля Chevrolet.", "art_num": "Арт. № 42348191", "price": "500" }
    ];
    $scope.sonic = [
        { "image": "images/chevy sonic/Accessories/acc_1.jpg", "header": "Lug Nut", "description": "Complement the wheels on your vehicle with these decorative Lug Nuts with Chrome Caps.", "art_num": "Арт. № 17800819", "price": "5" },
        { "image": "images/chevy sonic/Accessories/acc_2.jpg", "header": "Wheel Lock Kit", "description": "Help deter thieves from taking the wheels off your vehicle with this Wheel Lock Kit, which includes 4 locks and a unique key.", "art_num": "Арт. № 12498078", "price": "40" },
        { "image": "images/chevy sonic/Accessories/acc_3.jpg", "header": "Splash Guards", "description": "Custom-designed Molded Splash Guards fit directly behind the wheels to help protect against tire splash and mud. Specially designed for your vehicle, they include styling features that accent the exterior of your vehicle.", "art_num": "Арт. № 95953991", "price": "50" },
        { "image": "images/chevy sonic/Accessories/acc_4.jpg", "header": "Cargo Net", "description": "Keep items secure in the trunk with this Cargo Net. It attaches easily to the sides of the vehicle cargo area and prevents small items from shifting while in transit.", "art_num": "Арт. № 95964983", "price": "55" },
        { "image": "images/chevy sonic/Accessories/acc_5.jpg", "header": "Door Handles", "description": "Add an extra level of styling to your vehicle with these Chrome Door Handles and Liftgate/Trunk Appliques.", "art_num": "Арт. № 95964717", "price": "100" },
        { "image": "images/chevy sonic/Accessories/acc_6.jpg", "header": "Mirror Caps", "description": "Make a statement with Outside Rearview Mirror Covers. They are available in Chrome.", "art_num": "Арт. № 95950260", "price": "70" },
        { "image": "images/chevy sonic/Accessories/acc_7.jpg", "header": "Side Window Weather Deflector", "description": "These custom-molded Side Window Weather Deflectors let fresh air in while keeping rain sleet and snow out. Plus they help reduce wind noise and sunlight glare.", "art_num": "Арт. № 19352754", "price": "80" },
        { "image": "images/chevy sonic/Accessories/acc_8.jpg", "header": "Pedal Covers", "description": "Pedal Covers are a great way to personalize the interior of your Sonic. They are available for Sonic models with either manual or automatic transmission.", "art_num": "Арт. № 95057350", "price": "80" },
        { "image": "images/chevy sonic/Accessories/acc_9.jpg", "header": "Integrated Cargo Liner", "description": "This Cargo Tray helps contain items and spills with its raised outer lip. It features a heavy-duty, nonskid surface that fits the exact dimensions of your Sonic.", "art_num": "Арт. № 95971429", "price": "100" },
        { "image": "images/chevy sonic/Accessories/acc_10.jpg", "header": "Door Sill Plates", "description": "Enhance the appearance of your front and rear door sills with these Door Sill Plates. They are available in brushed stainless steel.", "art_num": "Арт. № 95954000", "price": "100" },
        { "image": "images/chevy sonic/Accessories/acc_11.jpg", "header": "Emblems", "description": "Dress up and accent the exterior of your Sonic with this Bowtie Emblem Package.", "art_num": "Арт. № 42475824", "price": "115" },
        { "image": "images/chevy sonic/Accessories/acc_12.jpg", "header": "Floor Mats - Carpet Replacement", "description": "Front and Rear Premium Carpet Floor Mats provide a factory fit for your Sonic with a quality carpeted upper surface to match your interior.", "art_num": "Арт. № 95331964", "price": "130" },
        { "image": "images/chevy sonic/Accessories/acc_13.jpg", "header": "Floor Mats - Premium All-Weather", "description": "These precision-designed Premium All-Weather Front and Rear Floor Mats fit the front and rear rows exactly. The deep-ribbed pattern collects rain, mud, snow and other debris for easy cleaning. Nibs on the back help keep them in place.", "art_num": "Арт. № 95332036", "price": "130" },
        { "image": "images/chevy sonic/Accessories/acc_14.jpg", "header": "Floor Mats - Premium Carpet", "description": "Front and Rear Premium Carpet Replacement Floor Mats provide a factory fit for your Sonic with a quality carpeted upper surface to match your interior.", "art_num": "Арт. № 95332034", "price": "130" },
        { "image": "images/chevy sonic/Accessories/acc_15.jpg", "header": "Cargo Organizer", "description": "This Cargo Organizer with collapsible wall and dividers allows you the flexibility to carry items of various sizes. Molded, high-grade, skid-resistant thermal plastic protects the rear cargo area. Black with Chevrolet Bowtie logo.", "art_num": "Арт. № 95483420", "price": "160" },
        { "image": "images/chevy sonic/Accessories/acc_16.jpg", "header": "Roof Rack Cross Rails", "description": "The Removable Roof Rack kit includes cross rails and all necessary mounting hardware to expand cargo capacity for your Sonic Sedan or Hatchback.", "art_num": "Арт. № 95293141", "price": "255" },
        { "image": "images/chevy sonic/Accessories/acc_17.jpg", "header": "Remote Start Kit", "description": "By pressing a button on the key fob, the Remote Start system starts your parked vehicle. Great for pre-warming or pre-cooling your vehicle. Seamlessly integrated with your vehicle's anti-theft and remote keyless entry systems.", "art_num": "Арт. № 95990000", "price": "275" },
        { "image": "images/chevy sonic/Accessories/acc_18.jpg", "header": "Spoiler", "description": "This one-piece, custom-molded Flushmount Spoiler Kit adds a sporty flair to your Sonic Sedan or Hatchback. Available in select body colors. Personalize your Sonic by adding this Rear Spoiler in either the same body-color or really stand out from the crowd by choosing a contrasting color. Other coordinating parts available include the Mirror Caps and painted Grille Surround.", "art_num": "Арт. № 95328355", "price": "300" },
        { "image": "images/chevy sonic/Accessories/acc_19.jpg", "header": "Cruise Control Kit", "description": "Adding Cruise Control to your Sonic lets you maintain your desired speed on long trips without having to manually press your foot on the accelerator.", "art_num": "Арт. № 95142787", "price": "340" },
        { "image": "images/chevy sonic/Accessories/acc_20.jpg", "header": "Suspension Package", "description": "This kit utilizes new front springs with new rear shocks assembled with a different spring. The rear springs and shocks are redesigned to accommodate the new suspension travel. It includes 4 springs and 2 shocks. Compatible with Hatchback without sports package.", "art_num": "Арт. № 23158162", "price": "350" },
        { "image": "images/chevy sonic/Accessories/acc_21.jpg", "header": "Interior Lighting", "description": "This Ambient Lighting Kit provides accent lighting to the footwell area of your Sonic with a touch of the on/off switch. Set your mood with six colors (Blue, Red, Green, White, Purple and Orange) and two intensity levels (Low and High). Change colors manually or allow the system to cycle through the colors automatically.", "art_num": "Арт. № 95319699", "price": "365" }
    ];
});